[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flaek_mxe = "GQdBArjknHVD3r4QesRZsmV1vwQfHyMW7Ue8Shtsaqf9"

[programs.devnet]
flaek_mxe = "GQdBArjknHVD3r4QesRZsmV1vwQfHyMW7Ue8Shtsaqf9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=36a6861e-bab9-4038-93bd-b196fe6adc61"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
